// <auto-generated />
using System;
using EvoFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvoFlow.Api.Migrations
{
    [DbContext(typeof(EvoFlowDbContext))]
    [Migration("20260411070238_AddEmailRecipients")]
    partial class AddEmailRecipients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvoFlow.Api.Models.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.FuelRecord", b =>
                {
                    b.Property<long>("FuelRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FuelRecordId"));

                    b.Property<decimal>("AmountGBP")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("FuelTypeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("OdometerKm")
                        .HasColumnType("int");

                    b.Property<int?>("PumpDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TransactionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeL")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FuelRecordId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("PumpDeviceId");

                    b.HasIndex("SiteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelRecords");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.FuelType", b =>
                {
                    b.Property<string>("FuelTypeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpDevice", b =>
                {
                    b.Property<int>("PumpDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PumpDeviceId"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfflineCount")
                        .HasColumnType("int");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Protocol")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypeBitsGeneral")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TypeBitsProtocol")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("PumpDeviceId");

                    b.HasIndex("SiteId");

                    b.ToTable("PumpDevices");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpFlowInfo", b =>
                {
                    b.Property<long>("PumpFlowInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpFlowInfoId"));

                    b.Property<decimal?>("AvgFlowRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("AvgTimeToFlow")
                        .HasColumnType("int");

                    b.Property<int?>("AvgTimeToPeakFlow")
                        .HasColumnType("int");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxTimeToFlow")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTimeToPeakFlow")
                        .HasColumnType("int");

                    b.Property<decimal>("NominalFlowRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PeakFlowRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("PumpMonitoringGradeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalPumpTrans")
                        .HasColumnType("int");

                    b.HasKey("PumpFlowInfoId");

                    b.HasIndex("PumpMonitoringGradeId");

                    b.ToTable("PumpFlowInfo");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpGradeTotals", b =>
                {
                    b.Property<long>("PumpGradeTotalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpGradeTotalsId"));

                    b.Property<string>("GradeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("GradeOption")
                        .HasColumnType("int");

                    b.Property<long>("PumpTotalsId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VolumeDiff")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VolumeTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PumpGradeTotalsId");

                    b.HasIndex("PumpTotalsId");

                    b.ToTable("PumpGradeTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoring", b =>
                {
                    b.Property<long>("PumpMonitoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpMonitoringId"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HiSpeedTrigFlow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PumpDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PumpMonitoringId");

                    b.HasIndex("PumpDeviceId");

                    b.ToTable("PumpMonitoring");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoringGrade", b =>
                {
                    b.Property<long>("PumpMonitoringGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpMonitoringGradeId"));

                    b.Property<int>("GradeOption")
                        .HasColumnType("int");

                    b.Property<int>("NoPeakHourZeroTrans")
                        .HasColumnType("int");

                    b.Property<long>("PumpMonitoringId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalPumpTrans")
                        .HasColumnType("int");

                    b.Property<int>("UptimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ZeroTrans")
                        .HasColumnType("int");

                    b.HasKey("PumpMonitoringGradeId");

                    b.HasIndex("PumpMonitoringId");

                    b.ToTable("PumpMonitoringGrade");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpStatus", b =>
                {
                    b.Property<long>("PumpStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpStatusId"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<int>("PumpDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubState2Bits")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SubStateBits")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("PumpStatusId");

                    b.HasIndex("PumpDeviceId");

                    b.ToTable("PumpStatus");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpTankConsumption", b =>
                {
                    b.Property<long>("PumpTankConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpTankConsumptionId"));

                    b.Property<long>("PumpGradeTotalsId")
                        .HasColumnType("bigint");

                    b.Property<string>("TankId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("VolumeDiff")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VolumeTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PumpTankConsumptionId");

                    b.HasIndex("PumpGradeTotalsId");

                    b.ToTable("PumpTankConsumption");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpTotals", b =>
                {
                    b.Property<long>("PumpTotalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PumpTotalsId"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MoneyDiff")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MoneyTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PumpDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TotType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("VolumeDiff")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VolumeTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PumpTotalsId");

                    b.HasIndex("PumpDeviceId");

                    b.ToTable("PumpTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("ClosingHour")
                        .HasColumnType("time");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("OpeningHour")
                        .HasColumnType("time");

                    b.Property<string>("PoleSign")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FleetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.FuelRecord", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.FuelType", "FuelType")
                        .WithMany("FuelRecords")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvoFlow.Api.Models.PumpDevice", "PumpDevice")
                        .WithMany("FuelRecords")
                        .HasForeignKey("PumpDeviceId");

                    b.HasOne("EvoFlow.Api.Models.Site", "Site")
                        .WithMany("FuelRecords")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvoFlow.Api.Models.Vehicle", "Vehicle")
                        .WithMany("FuelRecords")
                        .HasForeignKey("VehicleId");

                    b.Navigation("FuelType");

                    b.Navigation("PumpDevice");

                    b.Navigation("Site");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpDevice", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.Site", "Site")
                        .WithMany("PumpDevices")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpFlowInfo", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpMonitoringGrade", "PumpMonitoringGrade")
                        .WithMany("PumpFlowInfos")
                        .HasForeignKey("PumpMonitoringGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpMonitoringGrade");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpGradeTotals", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpTotals", "PumpTotals")
                        .WithMany("PumpGradeTotals")
                        .HasForeignKey("PumpTotalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoring", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpDevice", "PumpDevice")
                        .WithMany("PumpMonitorings")
                        .HasForeignKey("PumpDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpDevice");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoringGrade", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpMonitoring", "PumpMonitoring")
                        .WithMany("PumpMonitoringGrades")
                        .HasForeignKey("PumpMonitoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpMonitoring");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpStatus", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpDevice", "PumpDevice")
                        .WithMany("PumpStatuses")
                        .HasForeignKey("PumpDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpDevice");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpTankConsumption", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpGradeTotals", "PumpGradeTotals")
                        .WithMany("PumpTankConsumptions")
                        .HasForeignKey("PumpGradeTotalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpGradeTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpTotals", b =>
                {
                    b.HasOne("EvoFlow.Api.Models.PumpDevice", "PumpDevice")
                        .WithMany("PumpTotals")
                        .HasForeignKey("PumpDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpDevice");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.FuelType", b =>
                {
                    b.Navigation("FuelRecords");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpDevice", b =>
                {
                    b.Navigation("FuelRecords");

                    b.Navigation("PumpMonitorings");

                    b.Navigation("PumpStatuses");

                    b.Navigation("PumpTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpGradeTotals", b =>
                {
                    b.Navigation("PumpTankConsumptions");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoring", b =>
                {
                    b.Navigation("PumpMonitoringGrades");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpMonitoringGrade", b =>
                {
                    b.Navigation("PumpFlowInfos");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.PumpTotals", b =>
                {
                    b.Navigation("PumpGradeTotals");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.Site", b =>
                {
                    b.Navigation("FuelRecords");

                    b.Navigation("PumpDevices");
                });

            modelBuilder.Entity("EvoFlow.Api.Models.Vehicle", b =>
                {
                    b.Navigation("FuelRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
